### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by noplanman** [10up/MU-Migration#20]
I really like this plugin/package and am super grateful for your work on it!
Has been so incredibly helpful to me.

Would you be open for a general housekeeping of the code? I love nice-looking code and would love to contribute more.

The functionality would obviously stay the same, this is mainly for the visual poetry part of the code 😇 (with some extras of slight optimisations)

- [x] #21 Fix typos and grammar
- [x] #22 Clean up and complete docblocks
- [x] #23 Clean up code to comply with WordPress coding standards
- [ ] #24 Slight code optimisations/modifications

I set the points up as checkboxes, as I'd be making a PR for each one, to keep it manageable and easy for you to check the changes.

What do you say?

**Comment by nicholasio** [comment]
I'd love to see some improvements here. My only concern is with possibly introducing regression with "Slight code optimisations/modifications". Perhaps we should tackle #5 first. I have been avoiding making huge changes to the code until adding unit tests to the plugin. But I don't see huge risks with the first three items.

**Comment by noplanman** [comment]
> My only concern is with possibly introducing regression

Yes, I totally understand that and agree with you. Having unit tests will be great! (We'll continue that discussion on #5)

I'll start with the first 3 point of this issue to also become more familiar with the code 👍

**Comment by noplanman** [comment]
@nicholasio 
Have updated the top comment and added the first 3 PRs for you to check out.

**Comment by corradomatt** [comment]
Would you be open to a PR with updated documentation in the README.md and/or in the CLI output? Some things aren't complete / 100% clear.

**Comment by nicholasio** [comment]
@corradomatt sure. Feel free to submit a PR.
